datamash: Add explicit arguments to crosstab_print prototype
In C23, a prototype like `crosstab_print ()` implies that the function
will take no arguments. This conflicts with the definition
`crosstab_print (const struct crosstab* ct)`.

We can demonstrate the issue by running:

$ CFLAGS+="-std=c2x" ./configure && make

That resulted in the following error:

> src/crosstab.c:152:1: error: conflicting types for 'crosstab_print'; have 'void(const struct crosstab *)'
>   152 | crosstab_print (const struct crosstab* ct)
>       | ^~~~~~~~~~~~~~
> In file included from src/crosstab.c:34:
> src/crosstab.h:50:1: note: previous declaration of 'crosstab_print' with type 'void(void)'
>    50 | crosstab_print ();
>       | ^~~~~~~~~~~~~~